### ISSUE TITLE
ImportError when importing EnergySystemHandler on Python 3.13

### ISSUE THREAD

**Issue by wcoenraads** [EnergyTransition/pyESDL#7]
When importing `EnergySystemHandler` from `esdl.esdl_handler` on Python 3.13, I get the following error:
```
Traceback (most recent call last):
  File "/Users/westercoenraads/repro/hello.py", line 2, in <module>
    from esdl.esdl_handler import EnergySystemHandler
  File "/Users/westercoenraads/repro/.venv/lib/python3.13/site-packages/esdl/esdl_handler.py", line 24, in <module>
    from esdl import support_functions
  File "/Users/westercoenraads/repro/.venv/lib/python3.13/site-packages/esdl/support_functions.py", line 18, in <module>
    from importlib.resources import Resource
ImportError: cannot import name 'Resource' from 'importlib.resources' (/Users/westercoenraads/.local/share/uv/python/cpython-3.13.0rc2-macos-aarch64-none/lib/python3.13/importlib/resources/__init__.py). Did you mean: 'resources'?
```
The same code works fine on Python 3.12.

Full code to reproduce (on Python 3.13.0):
```python
import esdl
from esdl.esdl_handler import EnergySystemHandler

def main():
    e = esdl.WindPark()
    print("Hello from repro!")
```

**Comment by ewoudwerkman** [comment]
`from importlib.resources import Resource` is an import that is not used (and wrong) in `support_functions.py`. Is should have been `pyecore.resources.resource.Resource`.
We will release a new version with the fix.

**Comment by ewoudwerkman** [comment]
Fixed in pyESDL v24.11.0, see https://pypi.org/project/pyESDL/
